<!DOCTYPE html>
<?php
   session_start();
?>
<html lang="en">
<link rel="stylesheet" href="/css/admin.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<head>
<meta charset="UTF-8">
<title> UMP Parcel </title>
</head>
<body style="background-color: #e6f5ff;text-align:center;">
<header>
<p>&nbsp; &nbsp; &nbsp; &nbsp; <strong> UMP Parcel System &nbsp;&nbsp;&nbsp; <?=$_SESSION['login_user'];?></strong><p>
<div class = "topnav"> 
	<a class = "active" href="https://www.ump.edu.my/campus-map"><strong> Locate Us </strong></a>
	<a class = "active" href="https://www.ump.edu.my/en"> <strong>Help&Support </strong></a>
	<a class = "active" href="https://www.ump.edu.my/en"><strong>Contact Us</strong></a>
	<a class = "active" href="https://www.ump.edu.my/en/about"><strong>About</strong></a>
	<a class = "active" href="logout.php"><strong>Logout</strong></a>

</div>

</header>
<header2>
<div class = "a">
<p><a href="residentPage.php">
<img src="/css/logo-rasmi-ump.png"width="130" height="55" ></a>
</p>
</div>
<div class = "b">
&nbsp; &nbsp; &nbsp; &nbsp;
<div class="dropdown">
  <button class="dropbtn" style= "font-family: 'Recursive', sans-serif;"><strong>Manage User </strong></button>
  <div class="dropdown-content">
  </div></div>
  <div class="dropdown">
  <button class="dropbtn" style= "font-family: 'Recursive', sans-serif;"><strong>Goods Arrival</strong></button>
  <div class="dropdown-content">
  </div></div>
  <div class="dropdown">
  <button class="dropbtn" style= "font-family: 'Recursive', sans-serif;"><strong>Goods Collection</strong></button>
  <div class="dropdown-content">
  </div></div>
  <div class="dropdown">
  <button class="dropbtn" style= "font-family: 'Recursive', sans-serif;"><strong>Recipient</strong></button>
  <div class="dropdown-content">
  <a href="recepient.php">Goods List</a>
  <a href="goodslistSearchstatus.php">Status</a>
  <a href="goodslistCalculation.php">Calculation</a>
  <a href="goodslistReport.php">Report</a>
  </div></div>
  <div class="dropdown">
  <button class="dropbtn" style= "font-family: 'Recursive', sans-serif;"><strong>Complaints</strong></button>
  <div class="dropdown-content">
  <a href="complaint1.php">Make Complaints</a>
  <a href="selfview.php">View Complaints</a>
  </div></div>
</div>
</header2>

<div class="fixed-bg">
<div class = "container"> 
<p style = "color : white" > <strong>Resident Home Page</strong></p>
</div>
</div>

<br><br>
<h1><strong>Parcel Management Made Easy</strong> </h1>
<p> We are ready to serve you with our best services</p>
<br><br><br><br>
<h2><strong>KEY FEATURES</strong> </h2>

<div class="containers">
<div class="row3" style="align-items:center;">

        <div class="column3"  >
		<br><br><br><br><br>
          <strong style="font-size:20px;"> Analytics & Report</strong> 
		  <p>Spot trends to improve operations, streamline and scale your parcel management processes. </p>
		</div>
        <div class="column3"    >
            <img src= "/css/1.png" width="400" height="300">
        </div>
		
</div>
<div class="row3" style="align-items:center;">

        <div class="column3"  >
		<br><br><br><br><br>
          <strong style="font-size:20px;"> Recipient Notification</strong> 
		  <p>Automatically notify recipients when their packages are ready to be collected via Email. </p>
		</div>
        <div class="column3"    >
            <img src= "/css/2.png" width="400" height="300">
        </div>
		
</div>
<div class="row3" style="align-items:center;">

        <div class="column3"  >
		<br><br><br><br><br>
          <strong style="font-size:20px;"> Digital Delivery Log</strong> 
		  <p>See a live status or history of each parcel. Check information such as courrier info, recipient name, staff handling the delivery, photos and more. </p>
		</div>
        <div class="column3"    >
            <img src= "/css/3.png" width="400" height="300">
        </div>
		
</div>
</div>

<div class="fixed-bg2">

<p style = "color :white;font-size:30px;" > <strong>#There Is a Story</strong></p>
<p style = "color :white;font-size:30px;" > <strong>#Behind Every Mails & Parcels</strong></p>
</div>
<br><br><br>
<h2> Type of Users</h2>
<div class="row3" style="align-items:center;">

        <div class="column3"  >
		<br><br><br>
          <strong style="font-size:20px;"> Admin</strong> 
		  <p>Review all the reports generated by the system from each module. </p>
		  <p>Analyse the chart, table and consistently improve on the system.</p>
		</div>
        <div class="column3"    >
		<br><br><br>
            <strong style="font-size:20px;"> Mail Officer</strong> 
		  <p>Receive all the mails and parcels of students from the delivery courier. </p>
		  <p>Rearrange and key in the information into the system while waiting for collection.</p>
        </div>
		
</div>
<br>
<div class="row3" style="align-items:center;">

        <div class="column3"  >
		<br><br><br>
          <strong style="font-size:20px;"> Warden</strong> 
		  <p>Collect the mails and parcels from office and keep in the office of Recidential College. </p>
		  <p>Update the status while sending notifications to students in that Recidential College.</p>
		</div>
        <div class="column3"    >
		<br><br><br>
            <strong style="font-size:20px;"> Recipient</strong> 
		  <p>Students in UMP who is responsibe for the mails and parcels. </p>
		  <p>Review and comments on the parcels after receiving as feedbacks for admin.</p>
        </div>
		
</div>
<br><br><br><br>
<div class="footer">
<hr style="width:85%"><br>
  <div class="column2 left2" >
  <p style = "font-size : 20px"> <strong> Get Started </strong></p>
  <a class="noDecoration" href="https://www.ump.edu.my"><p style = "font-size : 15px;color:#b3b3b3;"> UMP Home </p> </a>
  <a class="noDecoration" href="/home"><p style = "font-size : 15px;color:#b3b3b3;"> UMP Parcel Home </p> </a>
  <a class="noDecoration" href="https://www.ump.edu.my/en/about"><p style = "font-size : 15px;color:#b3b3b3;"> About Us </p> </a>
    <br><br>
  </div> 
  
  <div class="column2 middle" >
  <p style = "font-size : 20px"> <strong> Follow Us </strong></p>
    <br> 
  <a href="https://www.facebook.com/universiti.malaysia.pahang" class="fa fa-facebook"></a>&nbsp;
  <a href="https://www.instagram.com/umpmalaysia/" class="fa fa-instagram"></a>&nbsp;
  <a href="https://www.youtube.com/user/umpmedia" class="fa fa-youtube"></a>&nbsp;
  <a href="https://www.google.com/search?q=UMP+Malaysia&rlz=1C1CHBF_enMY862MY862&sxsrf=ALeKk00xEvjH4pl72JYbjjQBcZ6yh_hyjQ%3A1620562595727&ei=o9KXYPz2K6TDpgekyIKwAg&oq=UMP+Malaysia&gs_lcp=Cgdnd3Mtd2l6EAMyCAguEJECEJMCMgIIADICCAAyBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BwgjEOoCECc6DQguEMcBEK8BEOoCECc6BAgjECc6CgguEMcBEK8BECc6BAgAEEM6BQgAEJECOggIABCxAxCDAToFCAAQsQM6AgguOgQILhBDOgcIABCHAhAUOggIABAWEAoQHlDtG1i9MmC-NGgBcAJ4AIABwwGIAYULkgEDNy42mAEAoAEBqgEHZ3dzLXdperABCsABAQ&sclient=gws-wiz&ved=0ahUKEwi81OqOyrzwAhWkoekKHSSkACYQ4dUDCA8&uact=5" class="fa fa-google"></a>

  
  </div>
  
  <div class="column2 right2" >
  <p style = "font-size : 20px"> <strong> Contact Us </strong></p>
  <p style = "font-size : 15px">Universiti Malaysia Pahang<br>
		26600 Pekan,<br>
		Pahang , Malaysia </p>
	<p style = "font-size : 15px"> Tel: +609 424 4651 (Hotline) </p>
    <p style = "font-size : 15px"> Email : umplibrary@ump.edu.my </p><br><br>
  
  </div>
  <br><br><br><br>
  <hr style="width:85%">
  <p style = "font-size : 12px">Copyright © 2021 . Team Google All rights reserved</p><br>

  </div>
</body>
</html>